# Generated by Django 5.2 on 2025-08-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('landmarks', models.TextField(max_length=600)),
                ('rooms_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PG_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DeatilPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notice_period', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('operating_since', models.IntegerField()),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deatils', to='PG.pg')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=10)),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Unisex', 'Unisex')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.CharField(choices=[('veg', 'veg'), ('Non-veg', 'Non-veg'), ('both', 'both'), ('Wifi', 'Wifi')], default='Not availabel')),
                ('AC', models.BooleanField(default=False)),
                ('Power_Backup', models.BooleanField(default=False)),
                ('Wifi', models.BooleanField(default=False)),
                ('Attached_Washroom', models.BooleanField(default=False)),
                ('Room_Cleaning', models.BooleanField(default=False)),
                ('Laundry', models.BooleanField(default=False)),
                ('warden', models.BooleanField(default=False)),
                ('fridge', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('food_charges', models.CharField(default='No charges')),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='PG.pg')),
            ],
        ),
        migrations.CreateModel(
            name='PG_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(null=True, upload_to='media/')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='PG.pg')),
            ],
        ),
        migrations.AddField(
            model_name='pg',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgs', to='PG.pg_owner'),
        ),
        migrations.CreateModel(
            name='PGRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_entry', models.BooleanField(default=True)),
                ('smoking', models.BooleanField(default=False)),
                ('drinking', models.BooleanField(default=False)),
                ('party', models.BooleanField(default=False)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='PG.pg')),
            ],
        ),
    ]
