# Generated by Django 5.2.5 on 2025-08-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('rooms_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PG_Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=10)),
                ('gender', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Unisex', 'Unisex')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('facilities', models.CharField(choices=[('AC', 'AC'), ('Power Backup', 'Power Backup'), ('Washing Machine', 'Washing Machine'), ('Wifi', 'Wifi'), ('Attached Washroom', 'Attached Washroom'), ('Room Cleaning', 'Room Cleaning'), ('Laundry', 'Laundry'), ('food-veg', 'food-veg'), ('food-nonveg', 'food-nonveg'), ('food-both', 'food-both')], max_length=255)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='PG.pg')),
            ],
        ),
        migrations.CreateModel(
            name='PG_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(null=True, upload_to='media/')),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='PG.pg')),
            ],
        ),
        migrations.AddField(
            model_name='pg',
            name='owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgs', to='PG.pg_owner'),
        ),
    ]
