# Generated by Django 5.2.5 on 2025-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpg',
            name='facilities',
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='AC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='Attached_Washroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='Laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='Power_Backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='Room_Cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='Wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='food',
            field=models.CharField(choices=[('veg', 'veg'), ('Non-veg', 'Non-veg'), ('both', 'both'), ('Wifi', 'Wifi')], default='Not availabel'),
        ),
    ]
