# Generated by Django 5.2 on 2025-08-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0002_remove_aboutpg_facilities_aboutpg_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpg',
            name='food_charges',
            field=models.CharField(default='No charges'),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpg',
            name='warden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pg',
            name='landmarks',
            field=models.TextField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeatilPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notice_period', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('operating_since', models.IntegerField()),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deatils', to='PG.pg')),
            ],
        ),
        migrations.CreateModel(
            name='PGRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_closing', models.DateTimeField(default=10)),
                ('visitor_entry', models.BooleanField(default=True)),
                ('smoking', models.BooleanField(default=False)),
                ('drinking', models.BooleanField(default=False)),
                ('party', models.BooleanField(default=False)),
                ('pg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='PG.pg')),
            ],
        ),
    ]
