# Generated by Django 5.2 on 2025-08-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0003_aboutpg_food_charges_aboutpg_fridge_aboutpg_tv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgrules',
            name='gate_closing',
        ),
    ]
